package commons;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class ListingTest {

    Listing listing;
    Board board;

    @BeforeEach
    void setUp() {
        board = new Board("board","accesskey","password");
        listing = new Listing("list",board);
    }

    @Test
    void setBoard() {
    }

    @Test
    void getListId() { // the id is autogenerated
    }

    @Test
    void getTitle() {
        assertEquals("list", listing.getTitle());
    }

    @Test
    void setTitle() {
        listing.setTitle("list2");
        assertEquals("list2", listing.getTitle());
    }

    @Test
    void getCards() {
        List<Card> cards = new ArrayList<>();
        assertEquals(cards,listing.getCards());
    }

    @Test
    public void testAddCard() {

        Card card = new Card("desc","name",new Date(),null,null,listing);
        listing.getCards().add(card);
        assertEquals(1, listing.getCards().size());
        assertTrue(listing.getCards().contains(card));
    }

    @Test
    void getBoard() {
        assertEquals(board,listing.getBoard());
    }

    @Test
    void testEquals() {
        Board board2 = new Board("board","accesskey","password");
        Listing listing2 = new Listing("list",board2);

        assertTrue(listing.equals(listing2));
    }

    @Test
    void testHashCode() {
        Board board2 = new Board("board","accesskey","password");
        Listing listing2 = new Listing("list",board2);

        assertEquals(listing.hashCode(),listing2.hashCode());
    }
}