package commons;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class TagTest {

    Tag tag;

    @BeforeEach
    void setUp() {
        tag = new Tag("tag");
    }

    @Test
    void getTagId() { // the id is autogenerated
    }

    @Test
    void getTitle() {
        assertEquals("tag",tag.getTitle());
    }

    @Test
    void setTitle() {
        tag.setTitle("tag2");
        assertEquals("tag2",tag.getTitle());
    }

    @Test
    void getCards() {
        List<Card> cards = new ArrayList<>();
        assertEquals(cards,tag.getCards());
    }

    @Test
    void setCards() {
        List<Card> cards = new ArrayList<>();
        Card card1 = new Card("desc","name",new Date(),null,null,null);
        cards.add(card1);

        Card card2 = new Card("desc","name2",new Date(),null,null,null);
        cards.add(card2);

        tag.setCards(cards);
        assertEquals(cards,tag.getCards());
    }

    @Test
    void testEquals() {
        Tag tag2 = new Tag("tag");
        assertTrue(tag.equals(tag2));
    }

    @Test
    void testHashCode() {
        Tag tag2 = new Tag("tag");
        assertEquals(tag.hashCode(),tag2.hashCode());
    }
}